name: Auto Update Votes & CR
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code du dépôt
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Installer les dépendances
        run: npm install axios adm-zip

      - name: Générer le nouveau votes.json
        run: node update_SCRUTIN.js

      - name: Générer le nouveau CR.json
        run: node update_CR.js

      - name: Enregistrer les modifications sur GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add votes.json CR.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: mise à jour automatique des votes et débats" && git push)
